In [24]:
import pandas as pd
import warnings

from sklearn.metrics import accuracy_score

warnings.filterwarnings('ignore')

In [25]:
data=pd.read_csv('Dry_Bean.csv')
from scipy.stats import skew

In [26]:
data.head(1)

Area  Perimeter  MajorAxisLength  MinorAxisLength  AspectRation  \
0  28395    610.291       208.178117       173.888747      1.197191   

   Eccentricity  ConvexArea  EquivDiameter    Extent  Solidity  roundness  \
0      0.549812       28715     190.141097  0.763923  0.988856   0.958027   

   Compactness  ShapeFactor1  ShapeFactor2  ShapeFactor3  ShapeFactor4  Class  
0     0.913358      0.007332      0.003147      0.834222      0.998724  SEKER

In [27]:
data['Class'].value_counts()

Class
DERMASON    3546
SIRA        2636
SEKER       2027
HOROZ       1928
CALI        1630
BARBUNYA    1322
BOMBAY       522
Name: count, dtype: int64

In [28]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 13611 entries, 0 to 13610
Data columns (total 17 columns):
 #   Column           Non-Null Count  Dtype  
---  ------           --------------  -----  
 0   Area             13611 non-null  int64  
 1   Perimeter        13611 non-null  float64
 2   MajorAxisLength  13611 non-null  float64
 3   MinorAxisLength  13611 non-null  float64
 4   AspectRation     13611 non-null  float64
 5   Eccentricity     13611 non-null  float64
 6   ConvexArea       13611 non-null  int64  
 7   EquivDiameter    13611 non-null  float64
 8   Extent           13611 non-null  float64
 9   Solidity         13611 non-null  float64
 10  roundness        13611 non-null  float64
 11  Compactness      13611 non-null  float64
 12  ShapeFactor1     13611 non-null  float64
 13  ShapeFactor2     13611 non-null  float64
 14  ShapeFactor3     13611 non-null  float64
 15  ShapeFactor4     13611 non-null  float64
 16  Class            13611 non-null  object 
dtypes: float64(1

In [29]:
data.describe().T

count          mean           std           min  \
Area             13611.0  53048.284549  29324.095717  20420.000000   
Perimeter        13611.0    855.283459    214.289696    524.736000   
MajorAxisLength  13611.0    320.141867     85.694186    183.601165   
MinorAxisLength  13611.0    202.270714     44.970091    122.512653   
AspectRation     13611.0      1.583242      0.246678      1.024868   
Eccentricity     13611.0      0.750895      0.092002      0.218951   
ConvexArea       13611.0  53768.200206  29774.915817  20684.000000   
EquivDiameter    13611.0    253.064220     59.177120    161.243764   
Extent           13611.0      0.749733      0.049086      0.555315   
Solidity         13611.0      0.987143      0.004660      0.919246   
roundness        13611.0      0.873282      0.059520      0.489618   
Compactness      13611.0      0.799864      0.061713      0.640577   
ShapeFactor1     13611.0      0.006564      0.001128      0.002778   
ShapeFactor2     13611.0      0.001716      0.000596      0.000564   
ShapeFactor3     13611.0      0.643590      0.098996      0.410339   
ShapeFactor4     13611.0      0.995063      0.004366      0.947687   

                          25%           50%           75%            max  
Area             36328.000000  44652.000000  61332.000000  254616.000000  
Perimeter          703.523500    794.941000    977.213000    1985.370000  
MajorAxisLength    253.303633    296.883367    376.495012     738.860154  
MinorAxisLength    175.848170    192.431733    217.031741     460.198497  
AspectRation         1.432307      1.551124      1.707109       2.430306  
Eccentricity         0.715928      0.764441      0.810466       0.911423  
ConvexArea       36714.500000  45178.000000  62294.000000  263261.000000  
EquivDiameter      215.068003    238.438026    279.446467     569.374358  
Extent               0.718634      0.759859      0.786851       0.866195  
Solidity             0.985670      0.988283      0.990013       0.994677  
roundness            0.832096      0.883157      0.916869       0.990685  
Compactness          0.762469      0.801277      0.834270       0.987303  
ShapeFactor1         0.005900      0.006645      0.007271       0.010451  
ShapeFactor2         0.001154      0.001694      0.002170       0.003665  
ShapeFactor3         0.581359      0.642044      0.696006       0.974767  
ShapeFactor4         0.993703      0.996386      0.997883       0.999733

In [30]:
X=data.drop(columns=['Class'])
y=data['Class']

In [31]:
print(X.shape)
print(y.shape)

(13611, 16)
(13611,)


In [32]:
skew=skew(X)
skew

array([ 2.95260553,  1.62594431,  1.35766564,  2.23796387,  0.58250919,
       -1.0627068 ,  2.9414969 ,  1.94874282, -0.89524975, -2.54981206,
       -0.63567889,  0.03711137, -0.53408168,  0.30119272,  0.2424542 ,
       -2.75917879])

In [33]:
from sklearn.preprocessing import StandardScaler
from sklearn.model_selection import train_test_split, cross_val_score
from sklearn.model_selection import KFold
from sklearn.ensemble import RandomForestClassifier
from xgboost import XGBClassifier
from sklearn.tree import DecisionTreeClassifier
from sklearn.linear_model import LogisticRegression
from sklearn.pipeline import Pipeline

In [34]:
import numpy as np

In [35]:
X=np.log1p(X)

In [36]:
print(X)

            Area  Perimeter  MajorAxisLength  MinorAxisLength  AspectRation  \
0      10.254004   6.415573         5.343186         5.164150      0.787180   
1      10.265871   6.459933         5.305912         5.213491      0.740678   
2      10.288103   6.437928         5.365163         5.175761      0.792862   
3      10.309253   6.472167         5.354499         5.212305      0.767159   
4      10.313642   6.431547         5.312456         5.253735      0.723093   
...          ...        ...              ...              ...           ...   
13606  10.647756   6.634234         5.668921         5.230813      0.937163   
13607  10.647851   6.631341         5.643949         5.256000      0.906822   
13608  10.648753   6.633741         5.643820         5.258474      0.905263   
13609  10.648943   6.639587         5.650321         5.253716      0.912012   
13610  10.649227   6.650586         5.690842         5.210604      0.963114   

       Eccentricity  ConvexArea  EquivDiameter    E

In [37]:
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.35,random_state=42)

In [38]:
print(X_train.shape,y_train.shape,X_test.shape,y_test.shape)

(8847, 16) (8847,) (4764, 16) (4764,)


In [39]:
from sklearn.preprocessing import LabelEncoder
from sklearn.svm import SVC
le=LabelEncoder()
y_train_final=le.fit_transform(y_train)
y_test_final=le.transform(y_test)
le_name_mapping = dict(zip(le.classes_, le.transform(le.classes_)))
print(le_name_mapping)

{'BARBUNYA': 0, 'BOMBAY': 1, 'CALI': 2, 'DERMASON': 3, 'HOROZ': 4, 'SEKER': 5, 'SIRA': 6}


In [40]:
print(y_train_final)

[3 3 4 ... 2 5 4]


In [41]:
print(y_test_final)

[5 0 5 ... 6 6 4]


In [42]:
models=[]
results=[]
pipelines=[]
names=[]
pipelines.append(('Scaled_LR',Pipeline(steps=[('scaler', StandardScaler()),('LR', LogisticRegression())])))
pipelines.append(('Scaled_Cart',Pipeline(steps=[('scaler', StandardScaler()),('Cart', DecisionTreeClassifier())])))
pipelines.append(('Scaled_RF',Pipeline(steps=[('scaler', StandardScaler()),('RF', RandomForestClassifier())])))
pipelines.append(('Scaled_XGB',Pipeline(steps=[('scaler', StandardScaler()),('XGB',XGBClassifier())])))
pipelines.append(('Scaled_SVC',Pipeline(steps=[('scaler', StandardScaler()),('SVC',SVC())])))
for name,model in pipelines:
    kfold = KFold(n_splits=10, shuffle=True, random_state=42)
    score=cross_val_score(model, X=X_train, y=y_train_final, cv=kfold)
    results.append(score)
    names.append(name)
    msg=("%s,%s,(%f)"% (name,score.mean(),score.std()))
    print(msg)



Scaled_LR,0.9227990387810927,(0.007130)
Scaled_Cart,0.8913779175294628,(0.011075)
Scaled_RF,0.9212169900554746,(0.009238)
Scaled_XGB,0.9227981440294499,(0.008222)
Scaled_SVC,0.9270943579517856,(0.005745)


In [50]:
#Hyperparameter Tuning for LR and SVC
parameters_LR={'penalty':['l1','l2','elasticnet'],'C':[0.01,0.02,0.03,0.05,1]}
from sklearn.model_selection import GridSearchCV
grid=GridSearchCV(LogisticRegression(),parameters_LR,cv=5)
grid.fit(X_train,y_train_final)
print(grid.best_params_)
print(grid.best_score_)

{'C': 1, 'penalty': 'l2'}
0.8845934854190022


In [52]:
from sklearn.metrics import accuracy_score

In [54]:
sc=StandardScaler()
from sklearn.ensemble import StackingClassifier
X_scaled_train=sc.fit_transform(X_train)
X_scaled_test=sc.transform(X_test)
estimators=[('lr',LogisticRegression()),('svc',SVC())]
st=StackingClassifier(estimators=estimators,final_estimator=LogisticRegression())
st.fit(X_scaled_train,y_train_final)
y_pred=st.predict(X_scaled_test)
print(round(accuracy_score(y_test_final,y_pred)*100,2))


92.84
